Check each element of server instead of casting to int
Fixes:
main/network.c:759:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
main/network.c:882:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
main/network.c:3278:4: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]