Remove unused function
Fixes:
In function ‘memcpy’,
    inlined from ‘multi_send_robot_controls’ at main/multi.c:4724:9:
/usr/include/x86_64-linux-gnu/bits/string3.h:52:3: error: call to __builtin___memcpy_chk will always overflow destination buffer [-Werror]