use memcpy instead of type-punning
Fixes:
arch/linux/linuxnet.c:190:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
arch/linux/linuxnet.c:192:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
arch/linux/linuxnet.c:415:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
arch/linux/ipx_bsd.c:150:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
arch/linux/ipx_bsd.c:196:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]